name: Build
on:
  [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'maven'
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build and Test
        run: mvn -B install
      - name: Deploy to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -Psign,deploy-github -DskipTests --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
      - uses: actions/setup-java@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          java-version: 21
          distribution: temurin
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy to OSSRH
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -Psign,deploy-central -DskipTests --no-transfer-progress
        env:
          MAVEN_OPTS: >
            --add-opens=java.base/java.util=ALL-UNNAMED
            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
            --add-opens=java.base/java.text=ALL-UNNAMED
            --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true