name: Build
on:
  [push]

env:
  JAVA_VERSION: 21

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: # Required for the attestations step
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'maven'
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
      - name: Build and Test
        run: mvn -B verify --no-transfer-progress

      - name: Deploy to Maven Central
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -Psign,deploy-central -DskipTests --no-transfer-progress
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          MAVEN_GPG_KEY_FINGERPRINT: ${{ vars.RELEASES_GPG_KEY_FINGERPRINT }}

      - uses: actions/setup-java@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: 'maven'
          gpg-private-key: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Deploy to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn -B deploy -Psign,deploy-github -DskipTests --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASES_GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.RELEASES_GPG_PRIVATE_KEY }}
          MAVEN_GPG_KEY_FINGERPRINT: ${{ vars.RELEASES_GPG_KEY_FINGERPRINT }}

      - name: Attest
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            target/jextract-maven-plugin-*.jar
            target/jextract-maven-plugin-*.pom

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true